### PR TITLE
Avoid divide by zero error

### PR DESCRIPTION
**Pull request by Danm72**
For a new DB this will crash out without deliveries

### CODE REVIEW

**Comment by kevinelliott** [comment]
I just pushed up **a lot** of changes. So you **might** need to look at this again. But I haven't looked at it, just giving you a heads up.

This is because I was contemplating not continuing a public repository for the site (and only keeping the gem open source), but I think it makes sense to keep the community site source open.

**Comment by kevinelliott** [comment]
@Danm72 Go ahead and fix the conflicts, and then we can merge.

**Comment by Danm72** [comment]
I'm not seeing where the conflicts lie, I merged our branches so I might be missing something.

In terms of making the source private, by all means don't let me stop you! I was forking to see how easy the bruteforce order numbers would be but I can live without it!

**Comment by kevinelliott** [comment]
You need to pull my master into your fork since there are new commits to my master. Then you have to look at any conflicts, commit the fixes, and push back up. Then this merge request should reflect the new changes.

No, I'll leave things public, I really enjoy the collaboration, so your exploration into brute forcing the numbers is kind of cool and I'd like to see you move forward!

**Comment by kevinelliott** [comment]
It looks like there's a conflict only in one file, so it shouldn't be difficult.

**Pull request closed without merging**
