### PR TITLE
Adding seeds for manufacturers and products

### PR DESCRIPTION
**Pull request by Danm72**
Expected output:
screen shot 2016-11-08 at 20 51 27

### CODE REVIEW

**Comment by kevinelliott** [comment]
This is great. Here's the data you need for manufacturers.json:

```
[{"id":1,"name":"DJI","code":"dji","description":"Leading manufacturer of consumer, prosumer, and professional drones and camera technology.","website":"http://www.dji.com/","support_email":"","support_website":"http://www.dji.com/support","logo_url":"http://www4.djicdn.com/assets/images/logo@2x-da7b16c3c5788410b42880cd8a8cfeca.png","created_at":"2016-11-02T01:39:33.933Z","updated_at":"2016-11-02T01:39:33.933Z","url":"https://www.dronehome.io/manufacturers/1.json"},{"id":2,"name":"GoPro","code":"gopro","description":"The most recognized action camera brand in the world, recently entered into the drone market.","website":"http://www.gopro.com/","support_email":"","support_website":"https://gopro.com/help","logo_url":"https://pbs.twimg.com/profile_images/775467646208704512/HgR6gVG2.jpg","created_at":"2016-11-02T01:40:37.752Z","updated_at":"2016-11-02T01:40:37.752Z","url":"https://www.dronehome.io/manufacturers/2.json"}]
```

**Comment by kevinelliott** [comment]
Also, here is `merchants.json`:

```
[{"id":2,"name":"Amazon","description":null,"website":"http://www.amazon.com","referral_code":null,"status":"pending","created_at":"2016-10-28T22:09:30.808Z","updated_at":"2016-10-28T22:09:30.808Z","url":"https://www.dronehome.io/merchants/2.json"},{"id":3,"name":"Amazon UK","description":null,"website":"http://uk.amazon.com","referral_code":null,"status":"pending","created_at":"2016-10-28T22:09:30.810Z","updated_at":"2016-10-28T22:09:30.810Z","url":"https://www.dronehome.io/merchants/3.json"},{"id":4,"name":"Best Buy","description":null,"website":"http://www.bestbuy.com","referral_code":null,"status":"pending","created_at":"2016-10-28T22:09:30.812Z","updated_at":"2016-10-28T22:09:30.812Z","url":"https://www.dronehome.io/merchants/4.json"},{"id":5,"name":"B\u0026H","description":null,"website":"http://www.bhphotovideo.com","referral_code":null,"status":"pending","created_at":"2016-10-28T22:09:30.815Z","updated_at":"2016-10-28T22:09:30.815Z","url":"https://www.dronehome.io/merchants/5.json"},{"id":6,"name":"NewEgg","description":null,"website":"http://www.newegg.com","referral_code":null,"status":"pending","created_at":"2016-10-28T22:09:30.817Z","updated_at":"2016-10-28T22:09:30.817Z","url":"https://www.dronehome.io/merchants/6.json"},{"id":1,"name":"Dà-Jiāng Innovations Science and Technology Co., Ltd","description":null,"website":"http://store.dji.com","referral_code":null,"status":"active","created_at":"2016-10-28T22:09:30.802Z","updated_at":"2016-11-07T08:25:17.137Z","url":"https://www.dronehome.io/merchants/1.json"}]
```

**Comment by Danm72** [comment]
Merchant seeds added

**Comment by Danm72** [comment]
Cool, can you merge?

**Comment by kevinelliott** [comment]
Yep, wanted to be sure you were done. Merging now!

**Comment by Danm72** [comment]
Cheers! 🍻

**Pull request merged**
